// @smarti/api - Orval-generated API hooks and Zod schemas
// This package is generated by Orval from openapi.json
// Do not edit manually - run `npm run generate` to regenerate

// Mutator factory — Apps must call initApiMutator() before first render
export { initApiMutator, apiMutator } from "./mutator";

// Re-export all generated hooks
export * from "./generated/hooks/content/content";
export * from "./generated/hooks/dashboard/dashboard";
export * from "./generated/hooks/ffg/ffg";
export * from "./generated/hooks/plan/plan";
export * from "./generated/hooks/session/session";
export * from "./generated/hooks/users/users";

// Re-export all generated schemas
export * from "./generated/schemas";
